package afcms:vsc-oxipng;

world vsc-oxipng {
    enum strip-metadata {
        none,
        safe,
        all,
    }

    import log: func(msg: string);
    export optimise: func(data: list<u8>, preset: u8, strip: strip-metadata) -> list<u8>;
}